"""Report generator — JSON, STIX 2.1, and natural-language threat briefs."""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from jinja2 import Environment, BaseLoader

from src.schemas import InvestigationResult

logger = logging.getLogger(__name__)

NL_BRIEF_TEMPLATE = """\
# Sietch Sentinel — Threat Brief
**Investigation ID:** {{ result.investigation_id }}
**Generated:** {{ now }}

---

## Target Satellite
| Field | Value |
|---|---|
| NORAD Cat ID | {{ result.norad_cat_id }} |
| Name | {{ result.satellite_name or "Unknown" }} |
| Orbit Regime | {{ result.orbit_regime.value }} |

## Anomaly Summary
- **Composite Score:** {{ "%.4f"|format(result.anomaly_score) }}
{% if result.delta_v %}\
- **Delta-V:** {{ "%.2f"|format(result.delta_v.delta_v_m_s) }} m/s ± {{ "%.2f"|format(result.delta_v.uncertainty_m_s) }} m/s
- **Confidence Interval:** [{{ "%.2f"|format(result.delta_v.confidence_interval[0]) }}, {{ "%.2f"|format(result.delta_v.confidence_interval[1]) }}]
{% endif %}

## Executive Summary
{{ result.executive_summary }}

{% if result.ttp_matches %}\
## TTP Matches
{% for ttp in result.ttp_matches %}\
- **[{{ ttp.framework }}] {{ ttp.technique_id }}** — {{ ttp.technique_name }}
  - Confidence: {{ ttp.confidence.value }}
  - Evidence: {{ ttp.evidence_summary }}
  - Natural causes ruled out: {{ ttp.natural_cause_ruled_out }}
{% endfor %}
{% endif %}

{% if result.data_gaps %}\
## Data Gaps
{% for gap in result.data_gaps %}\
- {{ gap }}
{% endfor %}
{% endif %}

{% if result.recommended_actions %}\
## Recommended Actions
{% for action in result.recommended_actions %}\
- {{ action }}
{% endfor %}
{% endif %}

## Resource Usage
- Tool calls: {{ result.tool_calls_used }}
- Tokens: {{ result.tokens_used }}
- Wall clock: {{ "%.1f"|format(result.wall_clock_seconds) }}s
{% if result.insufficient_data %}\

⚠️ **INSUFFICIENT DATA** — This investigation did not complete fully. Manual review required.
{% endif %}

---
*Generated by Sietch Sentinel v0.1.0*
"""


class ReportGenerator:
    """Generate multi-format reports from investigation results."""

    def __init__(self):
        self._jinja_env = Environment(loader=BaseLoader())
        self._nl_template = self._jinja_env.from_string(NL_BRIEF_TEMPLATE)

    def to_json(self, result: InvestigationResult) -> str:
        """Structured JSON report."""
        return result.model_dump_json(indent=2)

    def to_nl_brief(self, result: InvestigationResult) -> str:
        """Natural-language Markdown threat brief."""
        return self._nl_template.render(
            result=result,
            now=datetime.utcnow().isoformat(),
        )

    def save_reports(
        self,
        result: InvestigationResult,
        output_dir: Optional[Path] = None,
    ) -> dict[str, Path]:
        """Save all report formats to disk. Returns dict of format → path."""
        from src.config import settings

        output_dir = output_dir or settings.data_dir / "reports"
        output_dir.mkdir(parents=True, exist_ok=True)

        prefix = f"{result.investigation_id}"
        paths = {}

        # JSON
        json_path = output_dir / f"{prefix}.json"
        json_path.write_text(self.to_json(result), encoding="utf-8")
        paths["json"] = json_path

        # NL Brief (Markdown)
        md_path = output_dir / f"{prefix}_brief.md"
        md_path.write_text(self.to_nl_brief(result), encoding="utf-8")
        paths["markdown"] = md_path

        # STIX 2.1
        try:
            from src.reports.stix_builder import STIXBundleBuilder
            stix_builder = STIXBundleBuilder()
            bundle = stix_builder.build(result)
            stix_path = output_dir / f"{prefix}_stix.json"
            stix_path.write_text(bundle.serialize(pretty=True), encoding="utf-8")
            paths["stix"] = stix_path
        except ImportError:
            logger.warning("stix2 not installed — STIX report skipped.")
        except Exception as e:
            logger.error("STIX report generation failed: %s", e)

        logger.info("Reports saved: %s", {k: str(v) for k, v in paths.items()})
        return paths
